### ISSUE TITLE
URDF support

### ISSUE THREAD

**Issue by piotr-zyskowski-rai** [RobotecAI/o3de-ros2-gem#100]
**Is your feature request related to a problem? Please describe.**

Users would like to import Robot Definition files into simulations with o3de. Parsing and generating model from URDF is much better than trying to replicate it in supported formats.

**Describe the solution you'd like**
URDF file can be placed into Asset directory of a Project/Gem. They will be handled by the Asset Processor resulting in models/prefabs which can be added to the scene.

- [x] Importing: .urdf files
- [x] For basic support:
  - [x] geometry
    - [x] primitives
      - [x] box
      - [x] cylinder
      - [x] sphere
    - [x] meshes
  - [x] material
    - [x] color
    - [ ] textures
  - [x] colliders
  - [x] joints
    - [x] dependency tree 
    - [x] static
    - [x] dynamic
- [ ] Advanced support
  - [ ] handling scripting such as sensors (TBD)
  - [ ] exporting to URDF.
- [ ] An example included in the Gem

Old issue: https://github.com/o3de/o3de/issues/8483

**Comment by adamdbrw** [comment]
This is completed through #121 and tracked through other remaining tasks
