### ISSUE TITLE
Design of Vehicle Dynamics feature set

### ISSUE THREAD

**Issue by adamdbrw** [RobotecAI/o3de-ros2-gem#144]
The goal is to create Components and classes to support simulation of movement of diverse types of robot mobile bases. **The focus in this task should be narrowed down to the type required by the MS2 demo** (a four-wheeled, Ackermann drive type), with only rudimentary analysis of other types to understand what generalizations might be useful for the design. 
This task should include the following items:
* [x] Domain research, including available open-source solution (PhysX vehicle Gem, others) and solutions in other simulators.
* [x] Design of components and classes. How would a developer use the feature?

Outcomes:
* [x] Document capturing useful knowledge of how this feature is designed in existing solutions, comparison of major advantages and weaknesses.
* [x] First design document
* [x] Accepted design document, after a review.
* [x] Finally, a set of issues capturing implementation of the proposed design (some issues can be outside of MS2).

**Comment by adamdbrw** [comment]
[VehiclePhysics.pdf](https://github.com/RobotecAI/o3de-ros2-gem/files/9470489/VehiclePhysics.pdf)
First draft for reading.
This will be converted to a PR with docs
![ROSVehicleDynamics_planned](https://user-images.githubusercontent.com/16702721/187933297-8e157c5f-b010-4937-8b48-f5ad227a81ff.png)

**Comment by adamdbrw** [comment]
First iteration has been submitted.
Sub-tasks will include:
- Tasks for implementation of proposed components
- Tests on physics scene
- Implementation of a working example for a four-wheeled robot
- Second iteration of design

**Comment by pawelbudziszewski** [comment]
It seems fine to me, I have just one question regarding the diagram: why the WheelControllerComponent is connected to the VehicleModel via WheelsConfiguration, not directly? I'm not saying this is wrong, it just seems more natural for me if these wheel-related components are swapped places.

**Comment by adamdbrw** [comment]
WheelsConfiguration is a part of VehicleModel which holds (references) to WheelControllerComponents.

**Comment by pawelbudziszewski** [comment]
Ok for me
