### ISSUE TITLE
Move all the "build" things out of the PrefabMaker class

### ISSUE THREAD

**Issue by piotr-zyskowski-rai** [RobotecAI/o3de-ros2-gem#151]
All the "build" things could be moved out of the class to a separate one, to encapsulate this behavior.

likely we could do away with m_colliders being a shared_ptr if we do that.

_Originally posted by @adamdbrw in https://github.com/RobotecAI/o3de-ros2-gem/pull/142#discussion_r954900274_

**Comment by piotr-zyskowski-rai** [comment]
@adamdbrw This was done during the review right?

**Comment by adamdbrw** [comment]
No - this task is still valid, since they are in CollidersMaker now and could be separated out nicely.
