### ISSUE TITLE
Wheels collision shapes should be smoother

### ISSUE THREAD

**Issue by pawelbudziszewski** [RobotecAI/o3de-ros2-gem#231]
Cylinders representing wheel collision shapes should have 32 subdivisions or more. Currently, they have 16 which makes the ride bumpy.

**Comment by michalpelka** [comment]
@pawelbudziszewski, what number you recommend?

**Comment by michalpelka** [comment]
Here is PR: #232

**Comment by michalpelka** [comment]
Fixed with merged PR #232
