### ISSUE TITLE
Asset Processor asserts when starting up from batch

### ISSUE THREAD

**Issue by alek-kam** [RobotecAI/o3de-ros2-gem#238]
**Bug description**
When starting up Asset Processor from Batch, the Asset Builder's Class Builder asserts with a "You can attach attributes only to UiElements!" message.

**To Reproduce**

**Expected behavior**
The Asset Processor should run without any asserts triggered.

**Screenshots / videos**
![image](https://user-images.githubusercontent.com/108540351/192734761-b6aa9142-0c86-4020-bfdb-24b63b33ba01.png)

**Test environment**
Not specified.

**Comment by michalpelka** [comment]
Is this problem appearing only when o3de-ros2-gem is activated?

**Comment by adamdbrw** [comment]
This comes from ROS2SensorComponent reflection apparently.
But the only Attribute there is:
`->Attribute(AZ::Edit::Attributes::Category, "ROS2")`
Not sure what is wrong with this.

**Comment by adamdbrw** [comment]
@spham-amzn

**Comment by adamdbrw** [comment]
What is special about `ROS2SensorComponent`? My guess it is that it is the only base component (for `ROS2LidarSensorComponent`, for example). Base class has also this attribute specified. Maybe this is not legal?

**Comment by adamdbrw** [comment]
This one is fixed through removing of extra classification
