### ISSUE TITLE
Editor Gem Dependency prevets Game Launcher build 

### ISSUE THREAD

**Issue by adamdbrw** [RobotecAI/o3de-ros2-gem#260]
**Bug description**
Non-Editor target (ROS2.Static) is dependent on Az::AzToolsFramework. It should not be. 

**Additional context**
The only header with this dependency is ROS2GemUtilities.h. It calls AzToolsFramework::FindWrappedComponentForEntity<ComponentType>(entity);

This is because we have an Editor tool, URDF Importer, which dynamically creates components. We need our ROS 2 components to work well within Editor context as well as Game context, regardless of how they were created.

A proper solution should probably focus on how components are created instead.

**Comment by michalpelka** [comment]
Fixed in merged PR #326.
