### ISSUE TITLE
Realtime factor

### ISSUE THREAD

**Issue by michalpelka** [RobotecAI/o3de-ros2-gem#263]
**Is your feature request related to a problem? Please describe.**
It seems to me that the clock is published with the same pace - it does not slow down when simulation is slowing down (e.g. due to set m_maxTimeStep being set to a very small value). It makes a lot of ROS2 tools upset and renders simulated time pointless.

**Describe the solution you'd like**
Implement a more useful sim time mechanism. Publish or display realtime factors.

**Comment by adamdbrw** [comment]
Real time factor is part of time interface in O3DE and our Gem should already support it (our simulation clock takes time from a proper source)

**Comment by adamdbrw** [comment]
Closing this
