### ISSUE TITLE
ROS2 Spawner UI works incorrectly when adding more spawnables

### ISSUE THREAD

**Issue by pawelbudziszewski** [RobotecAI/o3de-ros2-gem#273]
**Bug description**
When adding more spawnables, UI behaves incorrectly - see screenshot

**Screenshots / videos**
![](https://user-images.githubusercontent.com/31925544/195199323-13f39e51-d141-4615-973d-c60dedab3a02.png)

**Test environment**
Tested on ROSCON demo

**Comment by adamdbrw** [comment]
This is likely a O3DE bug - I have seen this happen with other components, including ones outside of ROS 2 Gem and the Project.
Could you check whether there is such a bug reported in O3DE?

**Comment by adamdbrw** [comment]
This issue seems to be stale, possibly does not occur anymore
