### ISSUE TITLE
Robot Importer failed to load rightly URDF

### ISSUE THREAD

**Issue by danielemorra98** [RobotecAI/o3de-ros2-gem#275]
**Bug description**
When I am importing a robot model from URDF file, the O3DE engine crashes every time in the <collision> box there is a **cylinder** or a **sphere** geometry which measures are less than 1. It seems related to float numbers not correctly loaded (it rounds down floats, e.g. 0.5 becomes 0.0). This problem involves also the geometry of <visual> tag.

**To Reproduce**
Importing [this URDF](https://github.com/danielemorra98/limo_ros/blob/master/limo_description/urdf/sample.urdf) brings the engine about a crash.

**Screenshots / videos**
The resulting call stack:
![Screenshot from 2022-10-12 10-34-09](https://user-images.githubusercontent.com/48955695/195293270-e23e581b-c0fd-40fc-9e9d-04e8511c5a54.png)

**Test environment**
 - OS: Ubuntu 20.04
 - ROS2: Galactic

**Comment by adamdbrw** [comment]
@danielemorra98 it looks like a locale issue. Did you get a warning from the Importer? Could you share the logs?

This is likely ros2 urdfdom package parser.

**Comment by piotr-zyskowski-rai** [comment]
@danielemorra98 

Additionaly please share output of `locale` shell command. You should have output similar to this:
```
$ locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
```
For the URDF parsing case, `LC_NUMERIC="en_US.UTF-8"` is crucial

Also, to check whether it is in fact locale issue, you can use the command below to force the NUMERIC locale to be the US and in the same terminal execute the Editor binary. It should import correctly then.
```
export LC_NUMERIC="en_US.UTF-8"`
```

**Comment by adamdbrw** [comment]
FYI URDF importer is a kind of "Early Access" feature and has a lot of edges to be polished still. If you would like to help improving it, that would be great! Some issues are already listed.

**Comment by lgleim** [comment]
FYI - the PhysX crash when providing 0 as input to the `SetCylinderRadius` method was fixed two days ago in this commit: https://github.com/o3de/o3de/commit/147cd7460283fdb9c6d154d266506309a0efa808
Given the right locale, both issues should hopefully be handled. 

@piotr-zyskowski-rai Would it make sense to create a console warning whenever URDF parsing is conducted without `en_US.UTF-8` locale?

**Comment by adamdbrw** [comment]
@lgleim glad the change is in o3de. The warning should be there already with https://github.com/RobotecAI/o3de-ros2-gem/pull/197

**Comment by danielemorra98** [comment]
Thanks guys. In my locale settings there was:
`LC_NUMERIC=it_IT.UTF-8`
causing the issue.
