### ISSUE TITLE
 Ros2WarehouseDemo LUA script is not working

### ISSUE THREAD

**Issue by pawelbudziszewski** [RobotecAI/o3de-ros2-gem#302]
**Bug description**
In the Ros2WarehouseDemo, lua script raises an error:
```
Access to undeclared global variable 'TwistNotificationBus'
```
As a result, the robot is not moving. In the same time, the `RigidBodyTwistControlComponent` seems to work fine. The lua script is however the default option in the demo, so it fails to work right after `git clone`.

**Comment by adamdbrw** [comment]
This is Warehouse project issue
