### ISSUE TITLE
 Standards and styles / Miscellaneous / Part II

### ISSUE THREAD

**Issue by adamdbrw** [RobotecAI/o3de-ros2-gem#311]
Apply the following guidelines to the code base:
- [x] [RTTI](https://github.com/o3de/sig-core/blob/main/governance/Coding-Standards-and-Style-Guide.md#rtti)
- [x] [Casting](https://github.com/o3de/sig-core/blob/main/governance/Coding-Standards-and-Style-Guide.md#casting)
- [x] [Use of const](https://github.com/o3de/sig-core/blob/main/governance/Coding-Standards-and-Style-Guide.md#use-of-const)
- [x] [Don’t leave disabled code in the source](https://github.com/o3de/sig-core/blob/main/governance/Coding-Standards-and-Style-Guide.md#dont-leave-disabled-code-in-the-source)

**Comment by michalpelka** [comment]
There is still some unused code :
https://github.com/RobotecAI/o3de-ros2-gem/blob/008c13dccfef7df9cc9745c2df49a35b173e1b90/Assets/Scripts/SimpleTwistControl.lua
