### ISSUE TITLE
Standards and styles / Documentation 

### ISSUE THREAD

**Issue by adamdbrw** [RobotecAI/o3de-ros2-gem#312]
Ensure the documentation follows these guidelines:

- [x] [Self-documenting code is better than documenting the code yourself](https://github.com/o3de/sig-core/blob/main/governance/Coding-Standards-and-Style-Guide.md#self-documenting-code-is-better-than-documenting-the-code-yourself)
- [x]     [Use full sentences and avoid abbreviations](https://github.com/o3de/sig-core/blob/main/governance/Coding-Standards-and-Style-Guide.md#use-full-sentences-and-avoid-abbreviations)
- [x]     [Leave your feelings out of it](https://github.com/o3de/sig-core/blob/main/governance/Coding-Standards-and-Style-Guide.md#leave-your-feelings-out-of-it)
- [x]     [Use non-gendered pronouns](https://github.com/o3de/sig-core/blob/main/governance/Coding-Standards-and-Style-Guide.md#use-non-gendered-pronouns)
- [x]     [Explaining "why" is often more valuable than "what"](https://github.com/o3de/sig-core/blob/main/governance/Coding-Standards-and-Style-Guide.md#explaining-why-is-often-more-valuable-than-what)
- [x]     [Private members need love too](https://github.com/o3de/sig-core/blob/main/governance/Coding-Standards-and-Style-Guide.md#private-members-need-love-too)
- [x]     [Redundant documentation is redundant](https://github.com/o3de/sig-core/blob/main/governance/Coding-Standards-and-Style-Guide.md#redundant-documentation-is-redundant)
- [x]     [TODO comments](https://github.com/o3de/sig-core/blob/main/governance/Coding-Standards-and-Style-Guide.md#todo-comments)

**Comment by spham-amzn** [comment]
Review pass complete, will close out once comments are resolved or addressed

**Comment by spham-amzn** [comment]
Verified comments resolved
