### ISSUE TITLE
Standards and Styles / API Reference

### ISSUE THREAD

**Issue by adamdbrw** [RobotecAI/o3de-ros2-gem#313]
Ensure the Gem API follows the following guidelines:
https://github.com/o3de/sig-core/blob/main/governance/API-Ref-Guidelines-Update.md

Note that these should be in place already for the code comments so it should be a bit less work - hence not dividing this task further.
If something turns out to be more effort, additional task could be produced.

**Comment by adamdbrw** [comment]
@spham-amzn I did quite some improvement for this task with #332, possibly there is not much more to do but I will leave it for you to decide.

**Comment by spham-amzn** [comment]
@adamdbrw I've done a pass on the https://github.com/o3de/o3de-extras/pull/70 related to this task. Please look over when you get a chance, and once all the comments are resolved, I can close this issue
