### ISSUE TITLE
URDF importer does not preserve the hierarchy of entities

### ISSUE THREAD

**Issue by pawelbudziszewski** [RobotecAI/o3de-ros2-gem#324]
**Bug description**
Previously the URDF importer used to preserve the hierarchy of objects connected by joints and recreate this hierarchy in the O3DE entity tree. Now it inserts such objects on one level.

**To Reproduce**
1. Clone and build the [ROSConDemo](https://github.com/o3de/ROSConDemo/tree/urdf_update), branch `urdf_update`.
2. Follow the first 3 steps of [this tutorial](https://github.com/o3de/ROSConDemo/blob/urdf_update/docs/URDF_import/HOWTO_import_urdf.md)
3. Open the `apple_kraken_new` prefab

You'll see something like this (with all entities containing rigid bodies on one level):

![Screenshot from 2022-11-21 16-18-03](https://user-images.githubusercontent.com/31925544/203091973-ac53e086-6025-4f76-9acd-f0194c846763.png)

**Expected behavior**
It should look like this:

![Screenshot from 2022-11-21 16-20-08](https://user-images.githubusercontent.com/31925544/203092033-c40bbfc9-02aa-44d1-9864-3580d52ea942.png)

**Test environment**
Tested on:
- ROSConDemo [fdc70b197e6a43e099305dee08852a00714f522c](https://github.com/o3de/ROSConDemo/commit/fdc70b197e6a43e099305dee08852a00714f522c)
- O3DE [138e4a70a81770bd59fa7972c138e324c55441bd](https://github.com/o3de/o3de/commit/138e4a70a81770bd59fa7972c138e324c55441bd)
- o3de-ros2-gem [d5a76d2857e8f995191be8a4ac006e30db003f69](https://github.com/RobotecAI/o3de-ros2-gem/commit/d5a76d2857e8f995191be8a4ac006e30db003f69)

**Comment by michalpelka** [comment]
The hierarchy is created as flat, next it is established with `AZ::TransformBus::Events::SetParent`. Seems that `AZ::TransformBus::Events::SetParent` is ignored.  [Context](https://github.com/RobotecAI/o3de-ros2-gem/blob/development/Code/Source/RobotImporter/URDF/URDFPrefabMaker.cpp#L128)

**Comment by michalpelka** [comment]
fixed with #325
