### ISSUE TITLE
SourceAssetsStorage seems to be wastefull

### ISSUE THREAD

**Issue by michalpelka** [RobotecAI/o3de-ros2-gem#357]
**Is your feature request related to a problem? Please describe.**
The current implementation of the URDF importer during import builds its own asset catalog (`ROS2::Utils::GetInterestingSourceAssetsCRC`)
This shadow of the asset catalog consists of checksum and asset information. 
It is created for every mesh in the asset catalog - later the catalog is queried during import to resolve correct meshes.

**Describe the solution you'd like**
It is wasteful, consider:
 - limit scope to only sub-directory
 - consider typical optimization (e.g. lazy initialization)
 - benchmark if that is an issue, at all.

**Comment by adamdbrw** [comment]
After triage we determined this is not an issue for now, closing
