### ISSUE TITLE
Nav Stack: Create a Draft PR

### ISSUE THREAD

**Issue by forhalle** [RobotecAI/o3de-ros2-gem#362]
Similar #314, please create a Draft PR that can be reviewed for O3DE code standards (per #360).

**Comment by michalpelka** [comment]
Here is the PR with the navigation state (RO2 packages) migrated :
https://github.com/o3de/ROSConDemo/pull/202
This PR is created from main branch of this repository: https://github.com/RobotecAI/o3de_kraken_nav

**Comment by michalpelka** [comment]
Nav stack was merged to https://github.com/o3de/ROSConDemo/tree/development/kraken_nav.
