### ISSUE TITLE
Nav (Loft) Demo: Create a Draft PR

### ISSUE THREAD

**Issue by forhalle** [RobotecAI/o3de-ros2-gem#363]
Similar #314, please create a Draft PR that can be reviewed for O3DE code standards (per #361).

**Comment by michalpelka** [comment]
Created PR from loft demo (https://github.com/RobotecAI/o3de-demo-project) : https://github.com/o3de/o3de-extras/pull/77. Note it utilizes https://github.com/o3de/loft-arch-vis-sample.
It needs some tuning in readme and dockerfiles and testing.
